chains:
  - LLMChain
  - LLMMathChain
  - LLMBashChain
  - LLMChecker
  - ConversationChain

agents:
  - ZeroShotAgent
  - ConversationalChatAgent

prompts:
  - PromptTemplate
  - FewShotPromptTemplate

llms:
  - OpenAI
  - OpenAIChat
  - Cohere
  - BittensorLLM

vectorstores:
  # - Chroma

tools:
  - Search
  - PAL-MATH
  - Calculator
  - Serper Search

memories:
  - ConversationBufferMemory

dev: true
